package com.nar.ui;


import com.nar.Main;
import com.nar.model.Employee;
import com.nar.report.DailyPenjualanReport;
import com.nar.ui.master.BarangPanel;
import com.nar.ui.master.CustomerPanel;
import com.nar.ui.master.EmployeePanel;
import com.nar.ui.master.MasterAkunPanel;
import com.nar.ui.master.SupplierPanel;
import com.nar.ui.reports.DailyPenjualanReportPanel;
import com.nar.ui.reports.LabaRugiReportPanel;
import com.nar.ui.reports.NeracaSaldoReportPanel;
import com.nar.ui.reports.ReportCustomer;
import com.nar.ui.reports.ReportEmployee;
import com.nar.ui.transaksi.FormBiaya;
import com.nar.ui.transaksi.FormJurnalUmum;
import com.nar.ui.transaksi.FormPembelian;
import com.nar.ui.transaksi.FormPenjualan;
import java.beans.PropertyVetoException;
import javax.swing.JFrame;
import javax.swing.UIManager;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.log4j.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gunanto
 */
public class MenuUtama extends javax.swing.JFrame {

    private static final Logger log = Logger.getLogger(MenuUtama.class);
    private static Employee employee;
    /**
     * Creates new form MenuUtama
     */
    public MenuUtama(String user)
    {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        employee = (Employee) Main.getEmployeeService().getEmployee(user);
        checkUser();
        main();
    }

    public static Employee getEmployee() {
        return employee;
    }
    
    public void main()
    {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }
    
    private void checkUser()
    {
        if(employee.getNik().startsWith("mkt"))
        {
            mnuItemBarang.setEnabled(false);
            mnuItemKaryawan.setEnabled(false);
            mnuItemCustomer.setEnabled(true);
            mnuItemPenjualan.setEnabled(false);
            mnuItemPenjualanHarian.setEnabled(false);
        }
        else if(employee.getNik().startsWith("opt"))
        {
            mnuItemBarang.setEnabled(false);
            mnuItemKaryawan.setEnabled(false);
            mnuItemCustomer.setEnabled(false);
            mnuItemPenjualan.setEnabled(true);
            mnuItemPenjualanHarian.setEnabled(true);
        }
        else if(employee.getNik().startsWith("adm"))
        {
            mnuItemBarang.setEnabled(false);
            mnuItemKaryawan.setEnabled(false);
            mnuItemCustomer.setEnabled(false);
            mnuItemPenjualan.setEnabled(false);
            mnuItemPenjualanHarian.setEnabled(false);
        }
        else if(employee.getNik().startsWith("spv"))
        {
            mnuItemBarang.setEnabled(true);
            mnuItemKaryawan.setEnabled(true);
            mnuItemCustomer.setEnabled(true);
            mnuItemPenjualan.setEnabled(true);
            mnuItemPenjualanHarian.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mnuItemBarang = new javax.swing.JMenuItem();
        mnuItemKaryawan = new javax.swing.JMenuItem();
        mnuItemCustomer = new javax.swing.JMenuItem();
        mnuItemSupplier = new javax.swing.JMenuItem();
        mnuItemMasterAkun = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuItemPembelian = new javax.swing.JMenuItem();
        mnuItemPenjualan = new javax.swing.JMenuItem();
        mnuItemBiaya = new javax.swing.JMenuItem();
        mnuItemJurnalUmum = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mnuData = new javax.swing.JMenu();
        mnuItemEmployeeReport = new javax.swing.JMenuItem();
        mnuCustomerReport = new javax.swing.JMenuItem();
        mnuPenjualan = new javax.swing.JMenu();
        mnuItemPenjualanHarian = new javax.swing.JMenuItem();
        mnuPembelian = new javax.swing.JMenu();
        mnuAkuntasi = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuItemLogOut = new javax.swing.JMenuItem();
        mnuItemKluarProgram = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Penjualaan Barang");
        setBackground(new java.awt.Color(153, 153, 153));
        setName("jFrameMenuUtama"); // NOI18N

        jScrollPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("JTree");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Master");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Barang");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Karyawan");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Customer");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Nota");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Transaksi");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Penjualan");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Laporan");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Penjualan Harian");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setRootVisible(false);
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setViewportView(jDesktopPane1);

        jMenu3.setText("Master");

        mnuItemBarang.setText("Barang");
        mnuItemBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemBarangActionPerformed(evt);
            }
        });
        jMenu3.add(mnuItemBarang);

        mnuItemKaryawan.setText("Karyawan");
        mnuItemKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemKaryawanActionPerformed(evt);
            }
        });
        jMenu3.add(mnuItemKaryawan);

        mnuItemCustomer.setText("Customer");
        mnuItemCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCustomerActionPerformed(evt);
            }
        });
        jMenu3.add(mnuItemCustomer);

        mnuItemSupplier.setText("Supplier");
        mnuItemSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSupplierActionPerformed(evt);
            }
        });
        jMenu3.add(mnuItemSupplier);

        mnuItemMasterAkun.setText("Master Akun");
        mnuItemMasterAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemMasterAkunActionPerformed(evt);
            }
        });
        jMenu3.add(mnuItemMasterAkun);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Transaksi");

        mnuItemPembelian.setText("Pembelian");
        mnuItemPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemPembelianActionPerformed(evt);
            }
        });
        jMenu4.add(mnuItemPembelian);

        mnuItemPenjualan.setText("Penjualan");
        mnuItemPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemPenjualanActionPerformed(evt);
            }
        });
        jMenu4.add(mnuItemPenjualan);

        mnuItemBiaya.setText("Biaya");
        mnuItemBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemBiayaActionPerformed(evt);
            }
        });
        jMenu4.add(mnuItemBiaya);

        mnuItemJurnalUmum.setText("Jurnal Umum");
        mnuItemJurnalUmum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemJurnalUmumActionPerformed(evt);
            }
        });
        jMenu4.add(mnuItemJurnalUmum);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Laporan");

        mnuData.setText("Data");

        mnuItemEmployeeReport.setText("Employee");
        mnuItemEmployeeReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemEmployeeReportActionPerformed(evt);
            }
        });
        mnuData.add(mnuItemEmployeeReport);

        mnuCustomerReport.setText("Customer");
        mnuCustomerReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCustomerReportActionPerformed(evt);
            }
        });
        mnuData.add(mnuCustomerReport);

        jMenu5.add(mnuData);

        mnuPenjualan.setText("Penjualan");

        mnuItemPenjualanHarian.setText("Penjualan Harian");
        mnuItemPenjualanHarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemPenjualanHarianActionPerformed(evt);
            }
        });
        mnuPenjualan.add(mnuItemPenjualanHarian);

        jMenu5.add(mnuPenjualan);

        mnuPembelian.setText("Pembelian");
        jMenu5.add(mnuPembelian);

        mnuAkuntasi.setText("Akuntasi");

        jMenuItem1.setText("Laba / Rugi");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuAkuntasi.add(jMenuItem1);

        jMenuItem2.setText("Neraca Saldo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuAkuntasi.add(jMenuItem2);

        jMenu5.add(mnuAkuntasi);

        jMenuBar1.add(jMenu5);

        jMenu1.setText("Exit");

        mnuItemLogOut.setText("Log Out");
        mnuItemLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemLogOutActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItemLogOut);

        mnuItemKluarProgram.setText("Keluar Program");
        mnuItemKluarProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemKluarProgramActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItemKluarProgram);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(909, 656));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public BarangPanel barangPanel;
    private void mnuItemBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemBarangActionPerformed
        // TODO add your handling code here:
        try
        {
            if(barangPanel == null)
            {
                barangPanel = new BarangPanel();
                jDesktopPane1.add(barangPanel);
            }
            else
                barangPanel.toFront();
            barangPanel.setVisible(true);
            barangPanel.setSelected(true);
            barangPanel.setSize(jDesktopPane1.getSize());
        }
        catch (PropertyVetoException ex) 
        {
            log.error("error ketika menampilkan Barang panel", ex);
        }       
    }//GEN-LAST:event_mnuItemBarangActionPerformed

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        // TODO add your handling code here:
        String node = evt.getNewLeadSelectionPath().getLastPathComponent().toString();
        if( node.equals("Barang") ) 
        {
            mnuItemBarang.doClick();
        }
        else if( node.equals("Karyawan") )
        {
           mnuItemKaryawan.doClick();
        }
        else if(node.equals("Customer"))
        {
            mnuItemCustomer.doClick();
        }
        else if(node.equals("Penjualan"))
        {
            mnuItemPenjualan.doClick();
        }
        else if(node.equals("Penjualan Harian"))
        {
            mnuItemPenjualanHarian.doClick();
        }
    }//GEN-LAST:event_jTree1ValueChanged
    
    public EmployeePanel employeePanel;
    private void mnuItemKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemKaryawanActionPerformed
        // TODO add your handling code here:
        try
        {
            if(employeePanel == null)
            {
                employeePanel = new EmployeePanel();
                jDesktopPane1.add(employeePanel);
            }
            else
                employeePanel.toFront();
            employeePanel.setVisible(true);
            employeePanel.setSelected(true);
            employeePanel.setSize(jDesktopPane1.getSize());
        }
        catch (PropertyVetoException ex)
        {
            log.error("error ketika menampilkan Employee panel", ex);
        }
    }//GEN-LAST:event_mnuItemKaryawanActionPerformed
    
    public CustomerPanel customerPanel;
    private void mnuItemCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCustomerActionPerformed
        // TODO add your handling code here:
        try
        {
            if(customerPanel == null)
            {
                customerPanel = new CustomerPanel();
                jDesktopPane1.add(customerPanel);
            }
            else
                customerPanel.toFront();
            customerPanel.setVisible(true);
            customerPanel.setSelected(true);
            customerPanel.setSize(jDesktopPane1.getSize());
        }
        catch(PropertyVetoException ex)
        {
            log.error("error ketika menampilkan Customer panel");
        }
    }//GEN-LAST:event_mnuItemCustomerActionPerformed

    public FormPenjualan formPenjualan;
    private void mnuItemPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemPenjualanActionPerformed
        // TODO add your handling code here:
        try
        {
            if(formPenjualan == null)
            {
                formPenjualan = new FormPenjualan();
                jDesktopPane1.add(formPenjualan);
            }
            else
                formPenjualan.toFront();
            formPenjualan.setVisible(true);
            formPenjualan.setSelected(true);
            formPenjualan.setSize(jDesktopPane1.getSize());
        }
        catch(PropertyVetoException ex)
        {
            log.error("error ketika menampilkan Form Penjualan");
        }
    }//GEN-LAST:event_mnuItemPenjualanActionPerformed
    public DailyPenjualanReportPanel dailyPenjualanReportPanel;
    private void mnuItemPenjualanHarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemPenjualanHarianActionPerformed
        // TODO add your handling code here:
        try
        {
            if(dailyPenjualanReportPanel == null)
            {
                dailyPenjualanReportPanel = new DailyPenjualanReportPanel();
                jDesktopPane1.add(dailyPenjualanReportPanel);
            }
            else
                dailyPenjualanReportPanel.toFront();
            dailyPenjualanReportPanel.setVisible(true);
            dailyPenjualanReportPanel.setSelected(true);
            dailyPenjualanReportPanel.setSize(jDesktopPane1.getSize());
        }
        catch(PropertyVetoException ex)
        {
            log.error("error ketika menampilkan Daily Penjualan Report Panel");
        }
        
    }//GEN-LAST:event_mnuItemPenjualanHarianActionPerformed

    private void mnuItemKluarProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemKluarProgramActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuItemKluarProgramActionPerformed

    private void mnuItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemLogOutActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_mnuItemLogOutActionPerformed

    public ReportCustomer reportCustomer;
    private void mnuCustomerReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCustomerReportActionPerformed
        // TODO add your handling code here:
        try
        {
            if(reportCustomer == null)
            {
                reportCustomer = new ReportCustomer();
                jDesktopPane1.add(reportCustomer);
            }
            else
                reportCustomer.toFront();
            reportCustomer.setVisible(true);
            reportCustomer.setSelected(true);
            reportCustomer.setSize(jDesktopPane1.getSize());
        }
        catch(PropertyVetoException ex)
        {
            log.error("error ketika menampilkan Report Customer");
        }
    }//GEN-LAST:event_mnuCustomerReportActionPerformed
    
    public ReportEmployee reportEmployee;
    private void mnuItemEmployeeReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemEmployeeReportActionPerformed
        // TODO add your handling code here:
        try
        {
            if(reportEmployee == null)
            {
                reportEmployee = new ReportEmployee();
                jDesktopPane1.add(reportEmployee);
            }
            else
                reportEmployee.toFront();
            reportEmployee.setVisible(true);
            reportEmployee.setSelected(true);
            reportEmployee.setSize(jDesktopPane1.getSize());
        }
        catch(PropertyVetoException ex)
        {
            log.error("error ketika menampilkan Report Employee");
        }
    }//GEN-LAST:event_mnuItemEmployeeReportActionPerformed

    public SupplierPanel supplierPanel;
    private void mnuItemSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSupplierActionPerformed
        // TODO add your handling code here:
        try
        {
            if(supplierPanel == null)
            {
                supplierPanel = new SupplierPanel();
                jDesktopPane1.add(supplierPanel);
            }
            else
                supplierPanel.toFront();
            supplierPanel.setVisible(true);
            supplierPanel.setSelected(true);
            supplierPanel.setSize(jDesktopPane1.getSize());
        }
        catch(PropertyVetoException ex)
        {
            log.error("error ketika menampilkan form supplier Panel");
        }
    }//GEN-LAST:event_mnuItemSupplierActionPerformed

    private FormPembelian formPembelian;
    private void mnuItemPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemPembelianActionPerformed
        // TODO add your handling code here:
        try
        {
            if(formPembelian == null)
            {
                formPembelian = new FormPembelian();
                jDesktopPane1.add(formPembelian);
            }
            else
                formPembelian.toFront();
            formPembelian.setVisible(true);
            formPembelian.setSelected(true);
            formPembelian.setSize(jDesktopPane1.getSize());
        }
        catch(PropertyVetoException ex)
        {
            log.error("error ketika menampilkan Form Pembelian");
        }
    }//GEN-LAST:event_mnuItemPembelianActionPerformed

    private MasterAkunPanel masterAkunPanel;
    private void mnuItemMasterAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemMasterAkunActionPerformed
        // TODO add your handling code here:
        try
        {
            if(masterAkunPanel == null)
            {
                masterAkunPanel = new MasterAkunPanel();
                jDesktopPane1.add(masterAkunPanel);
            }
            else
                masterAkunPanel.toFront();
            masterAkunPanel.setVisible(true);
            masterAkunPanel.setSelected(true);
            masterAkunPanel.setSize(jDesktopPane1.getSize());
        }
        catch(PropertyVetoException ex)
        {
            log.error("error ketika menampilkan Master Akun Panel");
        }
    }//GEN-LAST:event_mnuItemMasterAkunActionPerformed

    private FormJurnalUmum formJurnalUmum;
    private void mnuItemJurnalUmumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemJurnalUmumActionPerformed
        // TODO add your handling code here:
        try
        {
            formJurnalUmum = new FormJurnalUmum();
            jDesktopPane1.add(formJurnalUmum);
            formJurnalUmum.toFront();
            formJurnalUmum.setVisible(true);
            formJurnalUmum.setSelected(true);
            formJurnalUmum.setSize(jDesktopPane1.getSize());
        }
        catch(PropertyVetoException ex)
        {
            log.error("error ketika menampilkan Form Jurnal Umum");
        }
    }//GEN-LAST:event_mnuItemJurnalUmumActionPerformed

    private FormBiaya formBiaya;
    private void mnuItemBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemBiayaActionPerformed
        // TODO add your handling code here:
        try
        {
            formBiaya = new FormBiaya();
            jDesktopPane1.add(formBiaya);
            formBiaya.toFront();
            formBiaya.setVisible(true);
            formBiaya.setSelected(true);
            formBiaya.setSize(jDesktopPane1.getSize());
        }
        catch(PropertyVetoException ex)
        {
            log.error("error ketika menampilkan Form Biaya");
        }
    }//GEN-LAST:event_mnuItemBiayaActionPerformed
    
    private LabaRugiReportPanel labaRugiReportPanel;
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try
        {
            if(labaRugiReportPanel == null)
            {
                labaRugiReportPanel = new LabaRugiReportPanel();
                jDesktopPane1.add(labaRugiReportPanel);
            }
            else
                labaRugiReportPanel.toFront();
            labaRugiReportPanel.setVisible(true);
            labaRugiReportPanel.setSelected(true);
            labaRugiReportPanel.setSize(jDesktopPane1.getSize());
        }
        catch(PropertyVetoException ex)
        {
            log.error("error ketika menampilkan Report Employee");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    private NeracaSaldoReportPanel neracaSaldoReportPanel;
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try
        {
            if(neracaSaldoReportPanel == null)
            {
                neracaSaldoReportPanel = new NeracaSaldoReportPanel();
                jDesktopPane1.add(neracaSaldoReportPanel);
            }
            else
                neracaSaldoReportPanel.toFront();
            neracaSaldoReportPanel.setVisible(true);
            neracaSaldoReportPanel.setSelected(true);
            neracaSaldoReportPanel.setSize(jDesktopPane1.getSize());
        }
        catch(PropertyVetoException ex)
        {
            log.error("error ketika menampilkan Report Employee");
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenu mnuAkuntasi;
    private javax.swing.JMenuItem mnuCustomerReport;
    private javax.swing.JMenu mnuData;
    private javax.swing.JMenuItem mnuItemBarang;
    private javax.swing.JMenuItem mnuItemBiaya;
    private javax.swing.JMenuItem mnuItemCustomer;
    private javax.swing.JMenuItem mnuItemEmployeeReport;
    private javax.swing.JMenuItem mnuItemJurnalUmum;
    private javax.swing.JMenuItem mnuItemKaryawan;
    private javax.swing.JMenuItem mnuItemKluarProgram;
    private javax.swing.JMenuItem mnuItemLogOut;
    private javax.swing.JMenuItem mnuItemMasterAkun;
    private javax.swing.JMenuItem mnuItemPembelian;
    private javax.swing.JMenuItem mnuItemPenjualan;
    private javax.swing.JMenuItem mnuItemPenjualanHarian;
    private javax.swing.JMenuItem mnuItemSupplier;
    private javax.swing.JMenu mnuPembelian;
    private javax.swing.JMenu mnuPenjualan;
    // End of variables declaration//GEN-END:variables
}
