package com.nar.ui;


import com.nar.Main;
import com.nar.report.DailyPenjualanReport;
import com.nar.ui.master.BarangPanel;
import com.nar.ui.master.CustomerPanel;
import com.nar.ui.master.EmployeePanel;
import com.nar.ui.master.NotaPanel;
import com.nar.ui.reports.DailyPenjualanReportPanel;
import com.nar.ui.transaksi.FormPenjualan;
import java.beans.PropertyVetoException;
import javax.swing.JFrame;
import javax.swing.UIManager;
import net.sf.jasperreports.view.JasperViewer;
import org.apache.log4j.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gunanto
 */
public class MenuUtama extends javax.swing.JFrame {

    private static final Logger log = Logger.getLogger(MenuUtama.class);
    private String user;
    /**
     * Creates new form MenuUtama
     */
    public MenuUtama(String user)
    {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.user = user;
        checkUser();
        main();
    }
    
    public void main()
    {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }
    
    private void checkUser()
    {
        if(user.startsWith("mkt"))
        {
            mnuItemBarang.setEnabled(false);
            mnuItemKaryawan.setEnabled(false);
            mnuItemCustomer.setEnabled(true);
            mnuItemNota.setEnabled(false);
            mnuItemPenjualan.setEnabled(false);
            mnuItemPenjualanHarian.setEnabled(false);
        }
        else if(user.startsWith("opt"))
        {
            mnuItemBarang.setEnabled(false);
            mnuItemKaryawan.setEnabled(false);
            mnuItemCustomer.setEnabled(false);
            mnuItemNota.setEnabled(false);
            mnuItemPenjualan.setEnabled(true);
            mnuItemPenjualanHarian.setEnabled(true);
        }
        else if(user.startsWith("adm"))
        {
            mnuItemBarang.setEnabled(false);
            mnuItemKaryawan.setEnabled(false);
            mnuItemCustomer.setEnabled(false);
            mnuItemNota.setEnabled(true);
            mnuItemPenjualan.setEnabled(false);
            mnuItemPenjualanHarian.setEnabled(false);
        }
        else if(user.startsWith("spv"))
        {
            mnuItemBarang.setEnabled(true);
            mnuItemKaryawan.setEnabled(true);
            mnuItemCustomer.setEnabled(true);
            mnuItemNota.setEnabled(true);
            mnuItemPenjualan.setEnabled(true);
            mnuItemPenjualanHarian.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mnuItemBarang = new javax.swing.JMenuItem();
        mnuItemKaryawan = new javax.swing.JMenuItem();
        mnuItemCustomer = new javax.swing.JMenuItem();
        mnuItemNota = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mnuItemPenjualan = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuCustomerReport = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnuItemPenjualanHarian = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        mnuItemLogOut = new javax.swing.JMenuItem();
        mnuItemKluarProgram = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Penjualaan Barang");
        setBackground(new java.awt.Color(153, 153, 153));
        setName("jFrameMenuUtama"); // NOI18N

        jScrollPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("JTree");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Master");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Barang");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Karyawan");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Customer");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Nota");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Transaksi");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Penjualan");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Laporan");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Penjualan Harian");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.setRootVisible(false);
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setViewportView(jDesktopPane1);

        jMenu3.setText("Master");

        mnuItemBarang.setText("Barang");
        mnuItemBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemBarangActionPerformed(evt);
            }
        });
        jMenu3.add(mnuItemBarang);

        mnuItemKaryawan.setText("Karyawan");
        mnuItemKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemKaryawanActionPerformed(evt);
            }
        });
        jMenu3.add(mnuItemKaryawan);

        mnuItemCustomer.setText("Customer");
        mnuItemCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCustomerActionPerformed(evt);
            }
        });
        jMenu3.add(mnuItemCustomer);

        mnuItemNota.setText("Nota");
        mnuItemNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemNotaActionPerformed(evt);
            }
        });
        jMenu3.add(mnuItemNota);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Transaksi");

        mnuItemPenjualan.setText("Penjualan");
        mnuItemPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemPenjualanActionPerformed(evt);
            }
        });
        jMenu4.add(mnuItemPenjualan);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Laporan");

        jMenuItem1.setText("Employee");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        mnuCustomerReport.setText("Customer");
        mnuCustomerReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCustomerReportActionPerformed(evt);
            }
        });
        jMenu5.add(mnuCustomerReport);

        jMenuItem2.setText("Nota");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        mnuItemPenjualanHarian.setText("Penjualan Harian");
        mnuItemPenjualanHarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemPenjualanHarianActionPerformed(evt);
            }
        });
        jMenu5.add(mnuItemPenjualanHarian);

        jMenuBar1.add(jMenu5);

        jMenu1.setText("Exit");

        mnuItemLogOut.setText("Log Out");
        mnuItemLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemLogOutActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItemLogOut);

        mnuItemKluarProgram.setText("Keluar Program");
        mnuItemKluarProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemKluarProgramActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItemKluarProgram);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-909)/2, (screenSize.height-656)/2, 909, 656);
    }// </editor-fold>//GEN-END:initComponents

    public BarangPanel barangPanel;
    private void mnuItemBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemBarangActionPerformed
        // TODO add your handling code here:
        try
        {
            if(barangPanel == null)
            {
                barangPanel = new BarangPanel();
                jDesktopPane1.add(barangPanel);
            }
            else
                barangPanel.toFront();
            barangPanel.setVisible(true);
            barangPanel.setSelected(true);
            barangPanel.setSize(jDesktopPane1.getSize());
        }
        catch (PropertyVetoException ex) 
        {
            log.error("error ketika menampilkan Barang panel", ex);
        }       
    }//GEN-LAST:event_mnuItemBarangActionPerformed

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        // TODO add your handling code here:
        String node = evt.getNewLeadSelectionPath().getLastPathComponent().toString();
        if( node.equals("Barang") ) 
        {
            mnuItemBarang.doClick();
        }
        else if( node.equals("Karyawan") )
        {
           mnuItemKaryawan.doClick();
        }
        else if(node.equals("Customer"))
        {
            mnuItemCustomer.doClick();
        }
        else if(node.equals("Nota"))
        {
            mnuItemNota.doClick();
        }
        else if(node.equals("Penjualan"))
        {
            mnuItemPenjualan.doClick();
        }
        else if(node.equals("Penjualan Harian"))
        {
            mnuItemPenjualanHarian.doClick();
        }
    }//GEN-LAST:event_jTree1ValueChanged
    
    public EmployeePanel employeePanel;
    private void mnuItemKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemKaryawanActionPerformed
        // TODO add your handling code here:
        try
        {
            if(employeePanel == null)
            {
                employeePanel = new EmployeePanel();
                jDesktopPane1.add(employeePanel);
            }
            else
                employeePanel.toFront();
            employeePanel.setVisible(true);
            employeePanel.setSelected(true);
            employeePanel.setSize(jDesktopPane1.getSize());
        }
        catch (PropertyVetoException ex)
        {
            log.error("error ketika menampilkan Employee panel", ex);
        }
    }//GEN-LAST:event_mnuItemKaryawanActionPerformed
    
    public CustomerPanel customerPanel;
    private void mnuItemCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCustomerActionPerformed
        // TODO add your handling code here:
        try
        {
            if(customerPanel == null)
            {
                customerPanel = new CustomerPanel();
                jDesktopPane1.add(customerPanel);
            }
            else
                customerPanel.toFront();
            customerPanel.setVisible(true);
            customerPanel.setSelected(true);
            customerPanel.setSize(jDesktopPane1.getSize());
        }
        catch(PropertyVetoException ex)
        {
            log.error("error ketika menampilkan Customer panel");
        }
    }//GEN-LAST:event_mnuItemCustomerActionPerformed

    public FormPenjualan formPenjualan;
    private void mnuItemPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemPenjualanActionPerformed
        // TODO add your handling code here:
        try
        {
            if(formPenjualan == null)
            {
                formPenjualan = new FormPenjualan(user);
                jDesktopPane1.add(formPenjualan);
            }
            else
                formPenjualan.toFront();
            formPenjualan.setVisible(true);
            formPenjualan.setSelected(true);
            formPenjualan.setSize(jDesktopPane1.getSize());
        }
        catch(PropertyVetoException ex)
        {
            log.error("error ketika menampilkan Form Penjualan");
        }
    }//GEN-LAST:event_mnuItemPenjualanActionPerformed
    public DailyPenjualanReportPanel dailyPenjualanReportPanel;
    private void mnuItemPenjualanHarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemPenjualanHarianActionPerformed
        // TODO add your handling code here:
        try
        {
            if(dailyPenjualanReportPanel == null)
            {
                dailyPenjualanReportPanel = new DailyPenjualanReportPanel();
                jDesktopPane1.add(dailyPenjualanReportPanel);
            }
            else
                dailyPenjualanReportPanel.toFront();
            dailyPenjualanReportPanel.setVisible(true);
            dailyPenjualanReportPanel.setSelected(true);
            dailyPenjualanReportPanel.setSize(jDesktopPane1.getSize());
        }
        catch(PropertyVetoException ex)
        {
            log.error("error ketika menampilkan Form Penjualan");
        }
        
    }//GEN-LAST:event_mnuItemPenjualanHarianActionPerformed

    private void mnuItemKluarProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemKluarProgramActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuItemKluarProgramActionPerformed

    private void mnuItemLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemLogOutActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_mnuItemLogOutActionPerformed
    public NotaPanel notaPanel;
    private void mnuItemNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemNotaActionPerformed
        // TODO add your handling code here:
        try
        {
            if(notaPanel == null)
            {
                notaPanel = new NotaPanel(user);
                jDesktopPane1.add(notaPanel);
            }
            else
                notaPanel.toFront();
            notaPanel.setVisible(true);
            notaPanel.setSelected(true);
            notaPanel.setSize(jDesktopPane1.getSize());
        }
        catch(PropertyVetoException ex)
        {
            log.error("error ketika menampilkan Form Penjualan");
        }
    }//GEN-LAST:event_mnuItemNotaActionPerformed

    private void mnuCustomerReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCustomerReportActionPerformed
        // TODO add your handling code here:
        JasperViewer.viewReport(Main.getReportService().getCustomerReport(),false);
    }//GEN-LAST:event_mnuCustomerReportActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JasperViewer.viewReport(Main.getReportService().getEmployeeReport(),false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JasperViewer.viewReport(Main.getReportService().getNotaReport(),false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenuItem mnuCustomerReport;
    private javax.swing.JMenuItem mnuItemBarang;
    private javax.swing.JMenuItem mnuItemCustomer;
    private javax.swing.JMenuItem mnuItemKaryawan;
    private javax.swing.JMenuItem mnuItemKluarProgram;
    private javax.swing.JMenuItem mnuItemLogOut;
    private javax.swing.JMenuItem mnuItemNota;
    private javax.swing.JMenuItem mnuItemPenjualan;
    private javax.swing.JMenuItem mnuItemPenjualanHarian;
    // End of variables declaration//GEN-END:variables
}
