/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nar.ui.transaksi;

import com.nar.Main;
import com.nar.model.JurnalUmum;
import com.nar.model.MasterAkun;
import com.nar.util.LineNumberTableRowHeader;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import org.apache.log4j.Logger;

/**
 *
 * @author Steven Gunanto
 */
public class FormBiaya extends javax.swing.JInternalFrame {

    private JurnalUmum jurnalUmum;
    private List<JurnalUmum> listJurnalUmum;
    
    private List<MasterAkun> listMasterAkun;
    
    private static final Logger log = Logger.getLogger(FormBiaya.class);
    
    /**
     * Creates new form Biaya
     */
    public FormBiaya() {
        initComponents();
        
        tableJurnalUmum.setAutoCreateColumnsFromModel(false);
        tableJurnalUmum.getSelectionModel().addListSelectionListener(new JurnalUmumSelectionListener());
        
        calendarComboBoxMulai.setDate(Main.getJurnalUmumService().getOldestDate());

        LineNumberTableRowHeader tableLineNumber = new LineNumberTableRowHeader(jScrollPane1, tableJurnalUmum);
        tableLineNumber.setBackground(Color.LIGHT_GRAY);
        jScrollPane1.setRowHeaderView(tableLineNumber);
        
        loadSortBy();
    }
    
    private void loadSortBy()
    {
        listMasterAkun = Main.getMasterAkunService().getAkuns("6%");
        for(MasterAkun masterAkun : listMasterAkun)
        {
            comboBoxSortBy.addItem(masterAkun.getNamaAkun());
        }
    }
    
    private void refreshTable()
    {
        listJurnalUmum = Main.getJurnalUmumService().getJurnalUmumBetween("6%",calendarComboBoxMulai.getDate(), calendarComboBoxSampai.getDate());
        tableJurnalUmum.setModel(new JurnalUmumTableModel(listJurnalUmum));
    }

    
    private class JurnalUmumTableModel extends AbstractTableModel
    {
        private List<JurnalUmum> listJurnalUmum;
        
        public JurnalUmumTableModel(List<JurnalUmum> listJurnalUmum) {
            this.listJurnalUmum = listJurnalUmum;
        }

        public void setDetailPembelian(List<JurnalUmum> listJurnalUmum) {
            this.listJurnalUmum = listJurnalUmum;
        }
        
        @Override
        public int getRowCount() {
            return listJurnalUmum.size();
        }

        @Override
        public int getColumnCount() {
            return 7;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            JurnalUmum j = listJurnalUmum.get(rowIndex);
            switch(columnIndex)
            {
                case 0:
                    return j.getTanggal();
                case 1:
                    return j.getMasterAkun().getKodeAkun();
                case 2:
                    return j.getMasterAkun().getNamaAkun();
                case 3:
                    return j.getFaktur();
                case 4:
                    long debet = j.getDk().equals("D") ? j.getSaldo() : 0;
                    return debet;
                case 5:
                    return j.getEmployee().getNama();
                default:
                    return "";
                        
            }
        }
        
    }
    
    private class JurnalUmumSelectionListener implements ListSelectionListener
    {
        public void valueChanged(ListSelectionEvent  e)
        {
            if(tableJurnalUmum.getSelectedRow() >= 0)
            {                
                jurnalUmum = listJurnalUmum.get(tableJurnalUmum.getSelectedRow());
                jurnalUmum = Main.getJurnalUmumService().getJurnalUmum(jurnalUmum.getId());
            }
            else
            {
                
            }
        }
    }
    
    private void clearForm()
    {
        refreshTable();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        calendarComboBoxMulai = new de.wannawork.jcalendar.JCalendarComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableJurnalUmum = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        calendarComboBoxSampai = new de.wannawork.jcalendar.JCalendarComboBox();
        jLabel2 = new javax.swing.JLabel();
        comboBoxSortBy = new javax.swing.JComboBox();

        setClosable(true);
        setTitle("Biaya");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setText("Mulai Tanggal");

        calendarComboBoxMulai.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                calendarComboBoxMulaiStateChanged(evt);
            }
        });

        tableJurnalUmum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Kode Akun", "Nama Akun", "Faktur", "Total Biaya Rp.", "Operator"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableJurnalUmum);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel6.setText("S/D");

        calendarComboBoxSampai.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                calendarComboBoxSampaiStateChanged(evt);
            }
        });

        jLabel2.setText("Sort By");

        comboBoxSortBy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Semua" }));
        comboBoxSortBy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxSortByItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addGap(17, 17, 17)
                                .addComponent(btnHapus))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(21, 21, 21)
                                .addComponent(calendarComboBoxMulai, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(calendarComboBoxSampai, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(calendarComboBoxMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel6)
                        .addComponent(calendarComboBoxSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(comboBoxSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calendarComboBoxMulaiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_calendarComboBoxMulaiStateChanged
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_calendarComboBoxMulaiStateChanged
    
    private TambahBiaya tambahBiaya;
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        if(tambahBiaya == null)
            tambahBiaya = new TambahBiaya(null, true);
        tambahBiaya.setLocationRelativeTo(null);
        tambahBiaya.setVisible(true);
        refreshTable();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if(jurnalUmum != null)
        {
            try
            {
                Main.getJurnalUmumService().delete(jurnalUmum.getFaktur());
                jurnalUmum = null;
                clearForm();
            }
            catch(Exception ex)
            {
                log.error(ex);
                JOptionPane.showMessageDialog(this, "Data masih digunakan tidak bisa dihapus!"
                    ,"Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void calendarComboBoxSampaiStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_calendarComboBoxSampaiStateChanged
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_calendarComboBoxSampaiStateChanged

    private void comboBoxSortByItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxSortByItemStateChanged
        // TODO add your handling code here:
        if(comboBoxSortBy.getSelectedIndex() == 0)
            refreshTable();
        else
        {
            listJurnalUmum = Main.getJurnalUmumService().getJurnalUmumBetween(listMasterAkun.get(comboBoxSortBy.getSelectedIndex() - 1).getKodeAkun(),calendarComboBoxMulai.getDate(), calendarComboBoxSampai.getDate());
            tableJurnalUmum.setModel(new JurnalUmumTableModel(listJurnalUmum));
        }
    }//GEN-LAST:event_comboBoxSortByItemStateChanged

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formInternalFrameActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private de.wannawork.jcalendar.JCalendarComboBox calendarComboBoxMulai;
    private de.wannawork.jcalendar.JCalendarComboBox calendarComboBoxSampai;
    private javax.swing.JComboBox comboBoxSortBy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableJurnalUmum;
    // End of variables declaration//GEN-END:variables
}
